bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid
loglevel notice
logfile ""
databases 1
save ""
appendonly no
dir /var/lib/redis
maxmemory 256mb
maxmemory-policy noeviction
